/**
 * App
 */
export const SET_APP_MESSAGE = 'SET_APP_MESSAGE';
export const SET_IS_LOADING = 'SET_IS_LOADING';
export const SET_MAIN_MENU_SELECTED = 'SET_MAIN_MENU_SELECTED';

/**
 * Authentication
 */
export const SET_IS_AUTHENTICATED = 'SET_IS_AUTHENTICATED';
export const SET_IS_CREDENTIAL_EXISTS = 'SET_IS_CREDENTIAL_EXISTS';

/**
 * Sign In
 */
export const SET_EMAIL = 'SET_EMAIL';
export const SET_PASSWORD = 'SET_PASSWORD';
export const SET_NAVIGATE_TO_HOME = 'SET_NAVIGATE_TO_HOME';
export const SET_NAVIGATE_TO_SIGN_IN = 'SET_NAVIGATE_TO_SIGN_IN';

/**
 * Students
 */
export const SET_STUDENT_INFO = 'SET_STUDENT_INFO';
export const RESET_STUDENTS_STATE = 'RESET_STUDENTS_STATE';

/**
 * Home
 */
export const SET_HOME_COURSE = 'SET_HOME_COURSE';
export const RESET_HOME_STATE = 'RESET_HOME_STATE';

/**
 * Search-Filter
 */
export const SET_LEVEL_FILTER = 'SET_LEVEL_FILTER';
export const SET_SUBJECT_FILTER = 'SET_SUBJECT_FILTER';
export const SET_SEARCH_KEYWORD = 'SET_SEARCH_KEYWORD';

/**
 * User
 */
export const SET_USER_DATA = 'SET_USER_DATA';
export const SET_USER_LOCAL_DATA = 'SET_USER_LOCAL_DATA';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_BIRTH_DATE = 'SET_USER_BIRTH_DATE';
export const SET_USER_BIO = 'SET_USER_BIO';
export const SET_USER_PHOTO = 'SET_USER_PHOTO';

/**
 * Assignment
 */
export const SET_ASSIGNMENT_TITLE = 'SET_TITLE';
export const SET_ASSIGNMENT_TYPE = 'SET_ASSIGNMENT_TYPE';
export const ADD_ASSIGNMENT_QUESTION = 'ADD_ASSIGNMENT_QUESTION';
export const EDIT_ASSIGNMENT_QUESTION = 'EDIT_ASSIGNMENT_QUESTION';
export const DELETE_ASSIGNMENT_QUESTION = 'DELETE_ASSIGNMENT_QUESTION';
export const REARRANGE_QUESTION_LIST = 'REARRANGE_QUESTION_LIST';
export const SET_ASSIGNMENT = 'SET_ASSIGNMENT';
export const RESET_STATE = 'RESET_STATE';

/**
 * Chapter Content
 */
export const SET_CHAPTER = 'SET_CHAPTER';
export const SET_CHAPTER_CONTENT = 'SET_CHAPTER_CONTENT';
export const SET_CHAPTER_ID = 'SET_CHAPTER_ID';
export const SET_CHAPTER_TITLE = 'SET_CHAPTER_TITLE';
export const SET_CHAPTER_SKETCHFAB = 'SET_CHAPTER_SKETCHFAB';

/**
 * Course Info
 */
export const SET_COURSE_INFORMATION = 'SET_COURSE_INFORMATION';
export const SET_COURSE_INFO_ARCHIVE = 'SET_COURSE_INFO_ARCHIVE';
export const ADD_PREREQUISITE_COURSES = 'ADD_PREREQUISITE_COURSES';
export const SET_PREREQUISITE_COURSES = 'SET_PREREQUISITE_COURSES';
export const ADD_RELATED_COURSES = 'ADD_RELATED_COURSES';
export const SET_RELATED_COURSES = 'SET_RELATED_COURSES';
export const SET_UNSUBSCRIBE_COURSE_INFO = 'SET_UNSUBSCRIBE_COURSE_INFO';

/**
 * Chapters
 */
export const SET_CHAPTERS = 'SET_CHAPTERS';
export const SET_CHAPTER_SEARCH_KEYWORD = 'SET_CHAPTER_SEARCH_KEYWORD';

/**
 * Discussions
 */
export const SET_CHAPTER_DISCUSSIONS = 'SET_CHAPTER_DISCUSSIONS';
export const SET_DISCUSSION_FORUMS = 'SET_DISCUSSION_FORUMS';
export const SET_DISCUSSION_SEARCH_KEYWORD = 'SET_DISCUSSION_SEARCH_KEYWORD';
export const SET_SELECTED_CHAPTER = 'SET_SELECTED_CHAPTER';
export const SET_IS_LOAD_CHAPTER_DISCUSSIONS = 'SET_IS_LOAD_CHAPTER_DISCUSSIONS';
export const SET_IS_LOAD_DISCUSSION_FORUMS = 'SET_IS_LOAD_DISCUSSION_FORUMS';

/**
 * Discussion Details
 */
export const SET_DISCUSSION_FORUM = 'SET_DISCUSSION_FORUM';
export const SET_DISCUSSION_ANSWERS = 'SET_DISCUSSION_ANSWERS';
export const SET_IS_LOAD_DISCUSSION_FORUM = 'SET_IS_LOAD_DISCUSSION_FORUM';
export const SET_IS_LOAD_DISCUSSION_ANSWERS = 'SET_IS_LOAD_DISCUSSION_ANSWERS';
export const SET_DISCUSSION_ANSWERS_SUBSCRIPTION = 'SET_DISCUSSION_ANSWERS_SUBSCRIPTION';
export const SET_REPLY_TEXT = 'SET_REPLY_TEXT';
export const SET_IS_SENDING_REPLY = 'IS_SENDING_REPLY';

/**
 * Add/Update Course
 */
export const SET_LEVEL = 'SET_LEVEL';
export const SET_TYPE = 'SET_TYPE';
export const SET_INFORMATION = 'SET_INFORMATION';
export const SET_TITLE = 'SET_TITLE';
export const SET_COVER_PICTURE = 'SET_COVER_PICTURE';
export const SET_DEFAULT_COVER_PICTURE = 'SET_DEFAULT_COVER_PICTURE';
export const SET_COURSES = 'SET_COURSES';
export const SET_RELATED_COURSE = 'SET_RELATED_COURSE';
export const SET_PREREQUISITE_COURSE = 'SET_PREREQUISITE_COURSE';
export const SET_IS_SUBMITTING_COURSE = 'SET_IS_SUBMITTING_MATERIAL';
export const SET_PREVIEW_COVER_PICTURE = 'SET_PREVIEW_COVER_PICTURE';
export const SET_ENROLLMENT_KEY = 'SET_ENROLLMENT_KEY';
export const SET_CHAPTER_SUMMARY_LIST = 'SET_CHAPTER_SUMMARY_LIST';
export const SET_IS_LOAD_COURSE = 'SET_IS_LOAD_COURSE';
export const SET_SUBMITTED_COURSE_ID = 'SET_SUBMITTED_COURSE_ID';
